//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTANCE_PARMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTANCE_PARMS()
        {
            this.SNAPSHOT_PARMS = new HashSet<SNAPSHOT_PARMS>();
        }
    
        public long INST_ID { get; set; }
        public System.DateTime STARTUP_TIME { get; set; }
        public string DB_VERSION { get; set; }
        public string INSTANCE_NAME { get; set; }
        public string HOST_NAME { get; set; }
        public string PLATFORM_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SNAPSHOT_PARMS> SNAPSHOT_PARMS { get; set; }
    }
}
