//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IO_PARMS
    {
        public long SNAP_ID { get; set; }
        public long INST_ID { get; set; }
        public string FILE_NAME { get; set; }
        public long BLOCK_READS { get; set; }
        public long BLOCK_WRITES { get; set; }
        public long TOTAL_IO { get; set; }
        public long WRITE_TIME { get; set; }
        public long READ_TIME { get; set; }
    
        public virtual SNAPSHOT_PARMS SNAPSHOT_PARMS { get; set; }
    }
}
