//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INSTANCE_PARMS> INSTANCE_PARMS { get; set; }
        public virtual DbSet<IO_PARMS> IO_PARMS { get; set; }
        public virtual DbSet<LATCH_PARMS> LATCH_PARMS { get; set; }
        public virtual DbSet<LIBRARY_CACHE_PARMS> LIBRARY_CACHE_PARMS { get; set; }
        public virtual DbSet<ROLLBACK_PARMS> ROLLBACK_PARMS { get; set; }
        public virtual DbSet<ROW_CACHE_PARMS> ROW_CACHE_PARMS { get; set; }
        public virtual DbSet<SESS_PARMS> SESS_PARMS { get; set; }
        public virtual DbSet<SNAPSHOT_PARMS> SNAPSHOT_PARMS { get; set; }
        public virtual DbSet<SQL_INFO_PARMS> SQL_INFO_PARMS { get; set; }
        public virtual DbSet<SYS_PARMS> SYS_PARMS { get; set; }
        public virtual DbSet<SYSSTAT_PARMS> SYSSTAT_PARMS { get; set; }
        public virtual DbSet<SYSTEM_EVENT_BG_PARMS> SYSTEM_EVENT_BG_PARMS { get; set; }
        public virtual DbSet<SYSTEM_EVENT_FG_PARMS> SYSTEM_EVENT_FG_PARMS { get; set; }
        public virtual DbSet<TIME_MODEL_PARMS> TIME_MODEL_PARMS { get; set; }
        public virtual DbSet<WAIT_CLASS_PARMS> WAIT_CLASS_PARMS { get; set; }
    
        public virtual int CHANGE_JOB_PRC(string jOB_NAME, string pARAM_NAME, string vAL_NEW)
        {
            var jOB_NAMEParameter = jOB_NAME != null ?
                new ObjectParameter("JOB_NAME", jOB_NAME) :
                new ObjectParameter("JOB_NAME", typeof(string));
    
            var pARAM_NAMEParameter = pARAM_NAME != null ?
                new ObjectParameter("PARAM_NAME", pARAM_NAME) :
                new ObjectParameter("PARAM_NAME", typeof(string));
    
            var vAL_NEWParameter = vAL_NEW != null ?
                new ObjectParameter("VAL_NEW", vAL_NEW) :
                new ObjectParameter("VAL_NEW", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CHANGE_JOB_PRC", jOB_NAMEParameter, pARAM_NAMEParameter, vAL_NEWParameter);
        }
    
        public virtual int DELETE_SNAPSHOTS_PRC(Nullable<decimal> fIRST_SNAP, Nullable<decimal> lAST_SNAP)
        {
            var fIRST_SNAPParameter = fIRST_SNAP.HasValue ?
                new ObjectParameter("FIRST_SNAP", fIRST_SNAP) :
                new ObjectParameter("FIRST_SNAP", typeof(decimal));
    
            var lAST_SNAPParameter = lAST_SNAP.HasValue ?
                new ObjectParameter("LAST_SNAP", lAST_SNAP) :
                new ObjectParameter("LAST_SNAP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_SNAPSHOTS_PRC", fIRST_SNAPParameter, lAST_SNAPParameter);
        }
    }
}
