//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNAPSHOT_PARMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SNAPSHOT_PARMS()
        {
            this.IO_PARMS = new HashSet<IO_PARMS>();
            this.SESS_PARMS = new HashSet<SESS_PARMS>();
            this.SQL_INFO_PARMS = new HashSet<SQL_INFO_PARMS>();
            this.SYS_PARMS = new HashSet<SYS_PARMS>();
            this.SYSSTAT_PARMS = new HashSet<SYSSTAT_PARMS>();
            this.SYSTEM_EVENT_BG_PARMS = new HashSet<SYSTEM_EVENT_BG_PARMS>();
            this.SYSTEM_EVENT_FG_PARMS = new HashSet<SYSTEM_EVENT_FG_PARMS>();
            this.TIME_MODEL_PARMS = new HashSet<TIME_MODEL_PARMS>();
            this.WAIT_CLASS_PARMS = new HashSet<WAIT_CLASS_PARMS>();
        }
    
        public long SNAP_ID { get; set; }
        public long INST_ID { get; set; }
        public System.DateTime SNAP_TIME { get; set; }
        public System.DateTime STARTUP_TIME { get; set; }
        public long SESSION_ID { get; set; }
        public long SERIAL_ { get; set; }
    
        public virtual INSTANCE_PARMS INSTANCE_PARMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IO_PARMS> IO_PARMS { get; set; }
        public virtual LATCH_PARMS LATCH_PARMS { get; set; }
        public virtual LIBRARY_CACHE_PARMS LIBRARY_CACHE_PARMS { get; set; }
        public virtual ROLLBACK_PARMS ROLLBACK_PARMS { get; set; }
        public virtual ROW_CACHE_PARMS ROW_CACHE_PARMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESS_PARMS> SESS_PARMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_INFO_PARMS> SQL_INFO_PARMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_PARMS> SYS_PARMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSSTAT_PARMS> SYSSTAT_PARMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_EVENT_BG_PARMS> SYSTEM_EVENT_BG_PARMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_EVENT_FG_PARMS> SYSTEM_EVENT_FG_PARMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIME_MODEL_PARMS> TIME_MODEL_PARMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAIT_CLASS_PARMS> WAIT_CLASS_PARMS { get; set; }
    }
}
