//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQL_INFO_PARMS
    {
        public long SNAP_ID { get; set; }
        public long INST_ID { get; set; }
        public string SQL_ID { get; set; }
        public long PARSE_CALLS { get; set; }
        public long LOADS { get; set; }
        public long INVALIDATIONS { get; set; }
        public long ELAPSED_TIME { get; set; }
        public long CPU_TIME { get; set; }
        public long EXECUTIONS { get; set; }
        public long APPLICATION_WAIT_TIME { get; set; }
        public long CONCURRENCY_WAIT_TIME { get; set; }
        public long USER_IO_WAIT_TIME { get; set; }
        public long PLSQL_EXEC_TIME { get; set; }
        public long JAVA_EXEC_TIME { get; set; }
        public long BUFFER_GETS { get; set; }
        public long DISK_READS { get; set; }
        public long DIRECT_WRITES { get; set; }
        public long ROWS_PROCESSED { get; set; }
        public long FETCHES { get; set; }
        public long SERIALIZABLE_ABORTS { get; set; }
    
        public virtual SNAPSHOT_PARMS SNAPSHOT_PARMS { get; set; }
    }
}
